### ISSUE TITLE
Remove ngrok from this repo

### ISSUE THREAD

**Issue by ghost** [CyberTitus/GPhisher#5]
PM for ngrok here. This tool directly violates the ngrok Terms of Service, even when used for educational purposes only.

We kindly request that ngrok be removed as an option in your repo.

ngrok is not anonymous and cannot be used to hide your identity. ngrok directly exposes your public IP address to anyone who sees the ngrok url you send them.

ngrok will ban your account if you use this tool.

Additionally, ngrok adds an interstitial page to all requests warning anyone viewing the page that the site is hosted by ngrok, notifying them that it is not the legitimate site you are attempting to mimic.

To learn more about how ngrok combats abuse, see https://ngrok.com/abuse and https://ngrok.com/tos

**Comment by AbdulRKB** [comment]
> ngrok is not anonymous and cannot be used to hide your identity. ngrok directly exposes your public IP address to anyone who sees the ngrok url you send them.
- Hello, This repo was made solely for educational & testing purposes so that the users can understand how phishing works. 
- This repo was not made to terminate or diminish cyber surveillance, or provide any sort of anonymity. It is not a problem if the public IP Address is exposed, since the users of this tool are less likely to send the tool to people whom they do not trust.

> Additionally, ngrok adds an interstitial page to all requests warning anyone viewing the page that the site is hosted by ngrok, notifying them that it is not the legitimate site you are attempting to mimic.
- That's even better, this will stop users of this tool from misusing the tool.

I have **removed** ngrok from this repo. Please have a look at the latest commit and verify whether ngrok has been removed so that I can close this issue. Thanks.

**Comment by ghost** [comment]
Thank you @CyberTitus, look good to me.
